version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build: 
      context: .
      dockerfile: ./backend.Dockerfile
    restart: always
    command: "java -jar notes.jar"
    ports:
      - '9001:9001'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:3001/notesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  db:
    build: 
      context: .
      dockerfile: ./db.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notesdb
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: -p 3001
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5